### ISSUE TITLE
Adding favicon to _quarto.yml

### ISSUE THREAD

**Issue by johannes4998** [hadley/r4ds#1139]
![1a2a649d-fcff-42d5-a9c4-a22773336ede](https://user-images.githubusercontent.com/18395884/202669941-0059d9ef-cf5e-4dc4-8814-713dbf57ec22.jpg)

It is very diffcult to navigate the diffrent R-books with many tabs open.

I would really like to see the book cover as favicon in the tab :slightly_smiling_face:

```
# _quarto.yml
book:
  title: "test-book"
  favicon: cover.png
```
